### ISSUE TITLE
Top `Current` elevation button excludes top layer

### ISSUE THREAD

**Issue by TaxiService** [plule/vox-uristi#1]
Hi! Like, i encountered a behaviour i consider unexpected.

When setting the elevation range, the top layer (the one you are looking at when you click the `Current` button) is excluded from the exported file.

Like, i would have expected it to be included. :p 

luckily i was able to record a webm of this within 10 MB 🤣 

[MagicaVoxel_S4Fpc3HasA.webm](https://user-images.githubusercontent.com/5853667/234010596-59a70d7c-f8ef-45b4-b62d-0fdaa613938e.webm)

as you can see, like, the top layer is missing from the model. 
If i go back in game, go down 1 layer, and click "Current" again, the elevation is lowered by one.

I mean-- this is totally a minor issue, i can easily work around it by going one level higher before exporting, but i think it is a bit counter-intuitive.
This could probably be fixed just as easily by changing a > to a >= somewhere, i guess? i mean, if you think this is a problem!

**Comment by plule** [comment]
Yep, that was intended but it makes much more sense to include it, thank you for the suggestion
